{
  enable = true;
  defaultApplications =
    let
      asignarAtributos = (
        lista: aplicacion:
        builtins.listToAttrs (
          map (mimeType: {
            name = mimeType;
            value = aplicacion;
          }) lista
        )
      );

      reproductorDeMusica = "io.bassi.Amberol.desktop";
      reproductorDeVideo = "org.gnome.Totem.desktop";
      exploradorDeArchivos = "org.gnome.Nautilus.desktop";
      manejadorDeArchivosComprimidos = "org.gnome.FileRoller.desktop";
      editorDeTexto = "neovim.desktop";

      audioMimeApps = [
        "audio/mpeg"
        "audio/mp3"
        "audio/mp4"
        "audio/x-m4a"
        "audio/flac"
        "audio/x-flac"
        "audio/ogg"
        "audio/x-vorbis+ogg"
        "audio/x-opus+ogg"
        "audio/wav"
        "audio/x-wav"
        "audio/aac"
        "audio/x-aac"
        "audio/webm"
        "audio/x-ms-wma"
        "audio/aiff"
        "audio/x-aiff"
        "audio/x-ape"
        "audio/x-wavpack"
        "audio/x-matroska"
        "audio/midi"
        "audio/x-midi"
      ];
      videoMimeTypes = [
        "video/mpeg"
        "video/mp4"
        "video/mp2t"
        "video/x-matroska"
        "video/x-matroska-3d"
        "video/webm"
        "video/x-msvideo"
        "video/avi"
        "video/quicktime"
        "video/x-flv"
        "video/x-flic"
        "video/x-ms-wmv"
        "video/x-ms-asf"
        "video/ogg"
        "video/x-ogm+ogg"
        "video/x-theora+ogg"
        "video/3gpp"
        "video/3gpp2"
        "video/divx"
        "video/mkv"
        "video/x-mpeg"
        "video/x-mpeg2"
        "video/x-nsv"
        "video/x-totem-stream"
      ];
      comprimidosMimeTypes = [
        "application/zip"
        "application/x-zip"
        "application/x-zip-compressed"
        "application/x-rar"
        "application/x-rar-compressed"
        "application/vnd.rar"
        "application/x-7z-compressed"
        "application/x-tar"
        "application/x-compressed-tar"
        "application/x-bzip-compressed-tar"
        "application/x-bzip2-compressed-tar"
        "application/x-xz-compressed-tar"
        "application/x-lzma-compressed-tar"
        "application/x-zstd-compressed-tar"
        "application/gzip"
        "application/x-gzip"
        "application/x-bzip"
        "application/x-bzip2"
        "application/x-xz"
        "application/x-lzma"
        "application/x-compressed"
        "application/x-lzip"
        "application/x-lzop"
        "application/zstd"
        "application/x-archive"
        "application/x-cpio"
        "application/x-ar"
        "application/x-arj"
        "application/x-lha"
        "application/x-lzh"
        "application/x-cab"
        "application/vnd.ms-cab-compressed"
        "application/x-stuffit"
        "application/x-ace"
        "application/x-alz"
        "application/x-iso9660-image"
        "application/x-cd-image"
      ];
      programacionMimeTypes = [
        "text/plain"
        "text/x-readme"
        "text/x-c"
        "text/x-csrc"
        "text/x-chdr"
        "text/x-c++"
        "text/x-c++src"
        "text/x-c++hdr"
        "text/x-java"
        "text/x-java-source"
        "text/x-python"
        "text/x-python3"
        "application/x-python"
        "text/javascript"
        "application/javascript"
        "application/x-javascript"
        "text/x-javascript"
        "application/json"
        "text/x-typescript"
        "application/typescript"
        "text/html"
        "application/xhtml+xml"
        "text/css"
        "text/x-scss"
        "text/x-sass"
        "text/x-less"
        "text/x-shellscript"
        "application/x-shellscript"
        "text/x-sh"
        "application/x-sh"
        "text/x-ruby"
        "application/x-ruby"
        "text/x-perl"
        "application/x-perl"
        "text/x-php"
        "application/x-php"
        "text/x-go"
        "text/x-rust"
        "text/x-haskell"
        "text/x-lua"
        "text/x-sql"
        "application/sql"
        "text/xml"
        "application/xml"
        "text/yaml"
        "text/x-yaml"
        "application/x-yaml"
        "text/x-toml"
        "application/toml"
        "text/x-ini"
        "text/x-config"
        "text/x-makefile"
        "text/x-cmake"
        "text/markdown"
        "text/x-markdown"
        "text/x-tex"
        "application/x-tex"
        "text/x-diff"
        "text/x-patch"
        "text/x-log"
        "text/x-asm"
        "text/x-fortran"
        "text/x-pascal"
        "text/x-lisp"
        "text/x-scheme"
        "text/x-emacs-lisp"
        "text/x-clojure"
        "text/x-scala"
        "text/x-kotlin"
        "text/x-swift"
        "text/x-r"
        "text/x-matlab"
        "text/x-octave"
        "text/x-julia"
        "text/x-nim"
        "text/x-zig"
        "text/x-elixir"
        "text/x-erlang"
        "text/x-dart"
        "text/x-coffeescript"
        "text/x-vue"
        "text/x-svelte"
        "text/x-nix"
        "text/x-dockerfile"
        "application/x-ipynb+json"
        "text/x-proto"
        "application/graphql"
        "text/x-terraform"
        "text/x-ansible"
      ];

    in
    {
      "inode/directory" = exploradorDeArchivos;
      "application/x-gnome-saved-search" = exploradorDeArchivos;
    }
    // asignarAtributos audioMimeApps reproductorDeMusica
    // asignarAtributos videoMimeTypes reproductorDeVideo
    // asignarAtributos comprimidosMimeTypes manejadorDeArchivosComprimidos
    // asignarAtributos programacionMimeTypes editorDeTexto;
}
